
name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code 
      - uses: actions/checkout@2
      
      - name: Create product env file 
      - working-directory: ./products
        run: | 
          touch .env
          echo APP_SECRET=jg_youtube_tutorial >> .env
          echo MONGODB_URI=mongodb://nosql-db:27017/product_ms_db >> .env
          echo MESSAGE_BROKER_URL=amqp://localhost >> .env
          echo PORT=8001 >> .env
          cat .env 
      - name: Create customer env file 
      - working-directory: ./customer
        run: | 
          touch .env
          echo APP_SECRET=jg_youtube_tutorial >> .env
          echo MONGODB_URI=mongodb://nosql-db:27017/customer_ms_db >> .env
          echo MESSAGE_BROKER_URL=amqp://localhost >> .env
          echo PORT=8002 >> .env
          cat .env 
      - name: Create shopping env file 
      - working-directory: ./shopping
        run: | 
          touch .env
          echo APP_SECRET=jg_youtube_tutorial >> .env
          echo MONGODB_URI=mongodb://nosql-db:27017/shopping_ms_db >> .env
          echo MESSAGE_BROKER_URL=amqp://localhost >> .env
          echo PORT=8003 >> .env
          cat .env 
        
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x "*.git'
          
      - name: Deploy on Elastic beanstalk QA Env
        uses: einaregilsson/beanstalk-deploy@20
        with:   
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets:AWS_SECRET_ACCESS_KEY}}
          application_name: test-ms
          environment_name: Testms-env
          version_label: "ver-${{github.sha}}"
          region: us-east-1
          deployment_package: deploy.zip
